import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";

const input="w-full rounded-xl px-3 py-2.5 outline-none";
const style:React.CSSProperties={background:"var(--glass)",border:"1px solid var(--line)",color:"var(--ink)"};
type Cat={offer?:{category_slug?:string;offer_type?:string};config:any;services:any[];resources:any[];rates:any[]};

export default function SellerBookingSetup(){
 const {offerId}=useParams();
 const [cat,setCat]=useState<Cat|null>(null); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 const [service,setService]=useState({name:"",description:"",duration:60,price:0,before:0,after:0});
 const [resource,setResource]=useState({name:"",kind:"staff",description:""});
 const [rate,setRate]=useState({from:"",to:"",price:0,minUnits:1,label:""});
 const [extras,setExtras]=useState({minUnits:1,maxUnits:30,cleaning:0,deposit:0,instant:true});
 async function load(){if(!offerId)return;const {data,error}=await supabase.schema("market").rpc("seller_booking_catalog_v2",{p_offer:offerId});if(error){setMsg(error.message);return;}const c=data as Cat;setCat(c);if(c?.config)setExtras({minUnits:Number(c.config.min_units||1),maxUnits:Number(c.config.max_units||30),cleaning:Number(c.config.cleaning_fee_gross||0),deposit:Number(c.config.deposit_gross||0),instant:Boolean(c.config.instant_booking)});}
 useEffect(()=>{load()},[offerId]);
 async function call(name:string,args:any){setBusy(true);setMsg("");const {error}=await supabase.schema("market").rpc(name,args);setBusy(false);if(error){setMsg(error.message);return false;}await load();setMsg("Zapisano ✅");return true;}
 if(!offerId)return <Shell><p>Brak oferty.</p></Shell>;
 const isDaily=cat?.config?.booking_type==="daily";
 const slug=String(cat?.offer?.category_slug||"");
 const isCarRental=isDaily&&slug.startsWith("motoryzacja-");
 return <Shell>
  <div className="mb-6"><Link to="/sprzedawca/oferty" className="text-sm underline" style={{color:"var(--mut)"}}>← Moje oferty</Link><h1 className="mt-2 font-display text-3xl font-semibold">Ustawienia bookingu</h1><p className="mt-1 text-sm" style={{color:"var(--mut)"}}>{isDaily?"Rezerwacja pobytu lub wynajmu jak Booking.com.":"Rezerwacja usług jak Booksy."}</p></div>
  {msg&&<div className="mb-4 rounded-xl p-3 text-sm" style={{background:"rgba(200,150,90,.12)",color:"var(--gold)"}}>{msg}</div>}
  {!cat?.config?<Card><h2 className="text-xl font-semibold">Najpierw włącz booking</h2><p className="mt-2 text-sm" style={{color:"var(--mut)"}}>W edycji oferty wybierz booking godzinowy albo wynajem na dni.</p></Card>:<div className="grid gap-5 lg:grid-cols-2">
   <Card><h2 className="text-xl font-semibold">Podstawy rezerwacji</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">
    {isDaily&&<><label className="text-sm">Minimalna liczba dni<input type="number" min="1" className={`${input} mt-1`} style={style} value={extras.minUnits} onChange={e=>setExtras({...extras,minUnits:Number(e.target.value)})}/></label><label className="text-sm">Maksymalna liczba dni<input type="number" min="1" className={`${input} mt-1`} style={style} value={extras.maxUnits} onChange={e=>setExtras({...extras,maxUnits:Number(e.target.value)})}/></label><label className="text-sm">Opłata przygotowawcza / sprzątanie<input type="number" min="0" className={`${input} mt-1`} style={style} value={extras.cleaning} onChange={e=>setExtras({...extras,cleaning:Number(e.target.value)})}/></label></>}
    {isCarRental&&<label className="text-sm">Kaucja za wynajem auta<input type="number" min="0" className={`${input} mt-1`} style={style} value={extras.deposit} onChange={e=>setExtras({...extras,deposit:Number(e.target.value)})}/><span className="mt-1 block text-xs" style={{color:"var(--mut)"}}>Opcjonalna. Nie jest używana przy usługach ani noclegach.</span></label>}
   </div><label className="mt-4 flex items-center justify-between rounded-xl p-3" style={{border:"1px solid var(--line)"}}><span><b>Rezerwacja natychmiastowa</b><span className="block text-xs" style={{color:"var(--mut)"}}>Po skutecznej płatności termin jest potwierdzony automatycznie.</span></span><input type="checkbox" checked={extras.instant} onChange={e=>setExtras({...extras,instant:e.target.checked})}/></label><button disabled={busy} onClick={()=>call("seller_booking_save_extras",{p_offer:offerId,p_min_units:extras.minUnits,p_max_units:extras.maxUnits,p_cleaning_fee:isDaily?extras.cleaning:0,p_deposit:isCarRental?extras.deposit:0,p_instant:extras.instant})} className="mt-4 w-full rounded-xl py-3 font-semibold text-black" style={{background:"linear-gradient(135deg,#C8965A,#E8C896)"}}>Zapisz ustawienia</button></Card>

   {!isDaily&&<Card><h2 className="text-xl font-semibold">Usługi</h2><p className="mt-1 text-sm" style={{color:"var(--mut)"}}>Każda usługa może mieć własną cenę i czas trwania — jak w Booksy.</p><div className="mt-4 space-y-2">{cat.services.map(s=><div key={s.id} className="flex items-center gap-3 rounded-xl p-3" style={{border:"1px solid var(--line)"}}><div className="flex-1"><b>{s.name}</b><div className="text-xs" style={{color:"var(--mut)"}}>{s.duration_minutes} min · {Number(s.price_gross).toLocaleString("pl-PL")} zł</div></div><button onClick={()=>call("seller_booking_service_delete",{p_offer:offerId,p_id:s.id})}>Usuń</button></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className={input} style={style} placeholder="Nazwa usługi" value={service.name} onChange={e=>setService({...service,name:e.target.value})}/><input type="number" className={input} style={style} placeholder="Cena" value={service.price||""} onChange={e=>setService({...service,price:Number(e.target.value)})}/><input type="number" className={input} style={style} placeholder="Czas w minutach" value={service.duration} onChange={e=>setService({...service,duration:Number(e.target.value)})}/><input className={input} style={style} placeholder="Krótki opis" value={service.description} onChange={e=>setService({...service,description:e.target.value})}/></div><button disabled={busy||!service.name} onClick={async()=>{if(await call("seller_booking_service_upsert",{p_offer:offerId,p_id:null,p_name:service.name,p_description:service.description,p_duration:service.duration,p_price:service.price,p_before:service.before,p_after:service.after,p_active:true}))setService({name:"",description:"",duration:60,price:0,before:0,after:0})}} className="mt-3 w-full rounded-xl py-2.5 font-semibold" style={{border:"1px solid var(--gold)",color:"var(--gold)"}}>+ Dodaj usługę</button></Card>}

   <Card><h2 className="text-xl font-semibold">{isDaily?"Obiekty / pojazdy":"Pracownicy i zasoby"}</h2><p className="mt-1 text-sm" style={{color:"var(--mut)"}}>{isDaily?"Auto, apartament, pokój lub inny obiekt, którego dostępność rezerwujesz.":"Pracownik lub sprzęt przypisywany do terminu usługi."}</p><div className="mt-4 space-y-2">{cat.resources.map(r=><div key={r.id} className="flex items-center gap-3 rounded-xl p-3" style={{border:"1px solid var(--line)"}}><div className="flex-1"><b>{r.name}</b><div className="text-xs" style={{color:"var(--mut)"}}>{r.kind}</div></div><button onClick={()=>call("seller_booking_resource_unlink",{p_offer:offerId,p_id:r.id})}>Odłącz</button></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className={input} style={style} placeholder="Nazwa" value={resource.name} onChange={e=>setResource({...resource,name:e.target.value})}/><select className={input} style={style} value={resource.kind} onChange={e=>setResource({...resource,kind:e.target.value})}>{!isDaily&&<option value="staff">Pracownik</option>}<option value="vehicle">Samochód</option><option value="property">Nieruchomość</option><option value="room">Pokój</option><option value="equipment">Sprzęt</option><option value="other">Inne</option></select></div><button disabled={busy||!resource.name} onClick={async()=>{if(await call("seller_booking_resource_upsert",{p_offer:offerId,p_id:null,p_name:resource.name,p_kind:resource.kind,p_description:resource.description,p_active:true}))setResource({name:"",kind:isDaily?"vehicle":"staff",description:""})}} className="mt-3 w-full rounded-xl py-2.5 font-semibold" style={{border:"1px solid var(--gold)",color:"var(--gold)"}}>+ Dodaj zasób</button></Card>

   {isDaily&&<Card><h2 className="text-xl font-semibold">Ceny sezonowe</h2><p className="mt-1 text-sm" style={{color:"var(--mut)"}}>Weekend, święta, wakacje, sezon wysoki — cena może zmieniać się zależnie od daty.</p><div className="mt-4 space-y-2">{cat.rates.map(r=><div key={r.id} className="flex items-center gap-3 rounded-xl p-3" style={{border:"1px solid var(--line)"}}><div className="flex-1"><b>{r.label||"Stawka specjalna"}</b><div className="text-xs" style={{color:"var(--mut)"}}>{r.starts_on} → {r.ends_on} · {r.price_per_unit?`${Number(r.price_per_unit).toLocaleString("pl-PL")} zł/dzień`:"cena bazowa"}</div></div><button onClick={()=>call("seller_booking_rate_delete",{p_offer:offerId,p_id:r.id})}>Usuń</button></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><input type="date" className={input} style={style} value={rate.from} onChange={e=>setRate({...rate,from:e.target.value})}/><input type="date" className={input} style={style} value={rate.to} onChange={e=>setRate({...rate,to:e.target.value})}/><input type="number" className={input} style={style} placeholder="Cena za dzień" value={rate.price||""} onChange={e=>setRate({...rate,price:Number(e.target.value)})}/><input className={input} style={style} placeholder="Nazwa, np. Wakacje" value={rate.label} onChange={e=>setRate({...rate,label:e.target.value})}/></div><button disabled={busy||!rate.from||!rate.to} onClick={async()=>{if(await call("seller_booking_rate_upsert",{p_offer:offerId,p_id:null,p_from:rate.from,p_to:rate.to,p_price:rate.price||null,p_min_units:rate.minUnits||null,p_label:rate.label,p_priority:0,p_active:true}))setRate({from:"",to:"",price:0,minUnits:1,label:""})}} className="mt-3 w-full rounded-xl py-2.5 font-semibold" style={{border:"1px solid var(--gold)",color:"var(--gold)"}}>+ Dodaj stawkę</button></Card>}
  </div>}
 </Shell>
}
function Card({children}:{children:React.ReactNode}){return <section className="rounded-2xl p-5" style={{background:"var(--glass)",border:"1px solid var(--line)"}}>{children}</section>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen px-4 py-8" style={{background:"var(--bg)",color:"var(--ink)"}}><div className="mx-auto max-w-6xl">{children}</div></main>}
