import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});

function kind(title:string,category:string){const s=`${title} ${category}`.toLowerCase();if(/samoch|motoryz|auto|pojazd/.test(s))return"vehicle";if(/nieruch|mieszkan|dom|apartament|działk|dzialk|lokal/.test(s))return"property";if(/usług|uslug|serwis|montaż|montaz|konsult|rezerw/.test(s))return"service";if(/wynajem|nocleg|hotel|apartament/.test(s))return"rental";if(/fotowolt|magazyn energ|pompa ciep|klimatyz|falownik|kocioł|piec/.test(s))return"energy";return"product"}
function structure(k:string,title:string){
 const intro=`## ${title}\n\n${title} to oferta przygotowana tak, aby klient od razu wiedział, co kupuje, dla kogo rozwiązanie jest przeznaczone i czego może się spodziewać po realizacji.`;
 if(k==="vehicle")return `${intro}\n\n## Najważniejsze informacje\n- stan i konfiguracja zgodnie z danymi ogłoszenia\n- możliwość umówienia oględzin\n- dane pojazdu mogą zostać sprawdzone przez Sunrise Verify\n\n## Stan i użytkowanie\nW opisie warto wskazać przebieg, wyposażenie, historię serwisową, znane ślady użytkowania oraz wszystkie informacje, które pomagają kupującemu ocenić auto przed kontaktem. Nie podajemy parametrów, których nie ma w danych oferty.\n\n## Zakup w Sunrise Market\nKlient może skontaktować się ze sprzedawcą, obserwować ofertę, porównać ją z innymi i — jeśli oferta ma aktywną rezerwację — umówić termin lub zarezerwować pojazd online.`;
 if(k==="property"||k==="rental")return `${intro}\n\n## Co wyróżnia ofertę\n- najważniejsze parametry nieruchomości zgodnie z danymi ogłoszenia\n- jasne warunki ceny i dostępności\n- możliwość kontaktu oraz rezerwacji online, jeśli booking jest aktywny\n\n## Dla kogo\nOpis powinien wyjaśniać przeznaczenie nieruchomości, lokalizację, układ, standard i najważniejsze udogodnienia bez dopisywania niepotwierdzonych informacji.\n\n## Rezerwacja i bezpieczeństwo\nPrzy ofertach rezerwacyjnych klient wybiera daty, widzi cenę okresu i przechodzi do płatności online. Dla wybranych nieruchomości może być dostępny Sunrise Verify.`;
 if(k==="service")return `${intro}\n\n## Zakres usługi\nOpisz konkretnie, co klient otrzymuje w cenie, ile trwa realizacja i co może wymagać dodatkowej wyceny.\n\n## Jak wygląda rezerwacja\nKlient może wybrać wariant usługi, dostępny termin oraz — jeśli sprzedawca skonfigurował zasoby — pracownika lub inny zasób. Rezerwacja może zostać opłacona online.\n\n## Przed realizacją\nWarto wskazać wymagania techniczne, przygotowanie po stronie klienta, obszar realizacji i zasady zmiany terminu.`;
 if(k==="energy")return `${intro}\n\n## Co obejmuje oferta\nZakres powinien jasno wskazywać urządzenie, montaż, konfigurację, uruchomienie i elementy dodatkowe wynikające z konkretnej oferty.\n\n## Korzyści\n- dopasowanie rozwiązania do obiektu\n- monitoring i obsługa w ekosystemie Sunrise\n- możliwość rozbudowy o kompatybilne elementy\n- serwis i historia obsługi w jednym miejscu\n\n## Ważne przed zakupem\nFinalny zakres zależy od warunków technicznych obiektu. Nie należy obiecywać parametrów lub oszczędności bez wcześniejszej analizy.`;
 return `${intro}\n\n## Najważniejsze zalety\n- przejrzysta cena i warunki zakupu\n- opis funkcji i zastosowania bez dopisywania niepotwierdzonych parametrów\n- możliwość zakupu w jednym ekosystemie Sunrise Market\n\n## Zastosowanie\nWyjaśnij, komu produkt się przyda i jaki problem rozwiązuje.\n\n## Zakup\nSzczegóły płatności, dostawy, odbioru, cashbacku i zwrotu powinny być pokazywane tylko wtedy, gdy dotyczą tej konkretnej oferty.`}

async function llm(title:string,category:string,action:string,current:string,key:string){const k=kind(title,category);const actionText=action==="improve"?"Popraw istniejący opis: zachowaj prawdziwe informacje, dodaj strukturę i konkret, usuń marketingowe ogólniki.":action==="shorten"?"Skróć opis o około 35%, zachowując wszystkie ważne fakty.":action==="expand"?"Rozwiń opis do profesjonalnej karty oferty z nagłówkami i listami, bez zmyślania danych.":"Napisz kompletny profesjonalny opis oferty.";const prompt=`Typ oferty: ${k}. Tytuł: ${title}. Kategoria: ${category||"brak"}. ${actionText}\n\nZasady: pisz po polsku, użyj Markdown (##, listy, pogrubienia), nie wymyślaj parametrów technicznych, cen, gwarancji, dostawy, cashbacku ani dostępności. Jeśli czegoś nie wiesz, pomiń. Nie używaj banałów typu 'najwyższa jakość'. Opis ma sprzedawać przez konkret.\n\nObecny opis:\n${current||"(brak)"}`;const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:"gpt-4o-mini",temperature:.55,messages:[{role:"system",content:"Jesteś polskim copywriterem marketplace i tworzysz rzetelne opisy bez zmyślania faktów."},{role:"user",content:prompt}]})});const j=await r.json();return j?.choices?.[0]?.message?.content||null}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const auth=req.headers.get("Authorization")??"";const uc=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:"Brak autoryzacji"},401);const body=await req.json();const title=String(body.title||"").trim();const category=String(body.category||"").trim();const action=String(body.action||"generate");const current=String(body.current_description||"").trim();if(!title&&action==="generate")return json({error:"Podaj nazwę oferty"},400);if(action!=="generate"&&!current)return json({error:"Brak opisu do edycji"},400);const key=Deno.env.get("OPENAI_API_KEY");let description:string|null=null;let used="standard";if(key){description=await llm(title,category,action,current,key);if(description)used="ai"}if(!description){if(action==="shorten")description=current.length>700?current.slice(0,Math.max(600,Math.round(current.length*.65))).replace(/\s+\S*$/,"…"):current;else if(action==="improve"||action==="expand")description=`${current}\n\n${structure(kind(title,category),title||"Oferta")}`.trim();else description=structure(kind(title,category),title||"Oferta");}return json({ok:true,description,mode:used,action});}catch(e){return json({error:String((e as Error).message||e)},400)}});