// Wspólne dane dla funkcji edge (strony miast dla robotów, sitemap). Ta sama lista co src/lib/cities.ts.
export const CITIES: { slug: string; name: string; region: string; km: number }[] = [{"slug": "nowy-tomysl", "name": "Nowy Tomyśl", "region": "wielkopolskie", "km": 0}, {"slug": "grodzisk-wielkopolski", "name": "Grodzisk Wielkopolski", "region": "wielkopolskie", "km": 19}, {"slug": "wolsztyn", "name": "Wolsztyn", "region": "wielkopolskie", "km": 22}, {"slug": "miedzyrzecz", "name": "Międzyrzecz", "region": "lubuskie", "km": 40}, {"slug": "swiebodzin", "name": "Świebodzin", "region": "lubuskie", "km": 41}, {"slug": "koscian", "name": "Kościan", "region": "wielkopolskie", "km": 44}, {"slug": "szamotuly", "name": "Szamotuły", "region": "wielkopolskie", "km": 45}, {"slug": "poznan", "name": "Poznań", "region": "wielkopolskie", "km": 55}, {"slug": "zielona-gora", "name": "Zielona Góra", "region": "lubuskie", "km": 60}, {"slug": "leszno", "name": "Leszno", "region": "wielkopolskie", "km": 61}, {"slug": "nowa-sol", "name": "Nowa Sól", "region": "lubuskie", "km": 64}, {"slug": "srem", "name": "Śrem", "region": "wielkopolskie", "km": 66}, {"slug": "glogow", "name": "Głogów", "region": "dolnośląskie", "km": 73}, {"slug": "gorzow-wielkopolski", "name": "Gorzów Wielkopolski", "region": "lubuskie", "km": 77}, {"slug": "pila", "name": "Piła", "region": "wielkopolskie", "km": 101}, {"slug": "zary", "name": "Żary", "region": "lubuskie", "km": 101}, {"slug": "gniezno", "name": "Gniezno", "region": "wielkopolskie", "km": 102}, {"slug": "lubin", "name": "Lubin", "region": "dolnośląskie", "km": 102}, {"slug": "legnica", "name": "Legnica", "region": "dolnośląskie", "km": 124}, {"slug": "ostrow-wielkopolski", "name": "Ostrów Wielkopolski", "region": "wielkopolskie", "km": 137}, {"slug": "konin", "name": "Konin", "region": "wielkopolskie", "km": 145}, {"slug": "wroclaw", "name": "Wrocław", "region": "dolnośląskie", "km": 148}, {"slug": "kalisz", "name": "Kalisz", "region": "wielkopolskie", "km": 148}, {"slug": "inowroclaw", "name": "Inowrocław", "region": "kujawsko-pomorskie", "km": 154}, {"slug": "bydgoszcz", "name": "Bydgoszcz", "region": "kujawsko-pomorskie", "km": 155}, {"slug": "szczecin", "name": "Szczecin", "region": "zachodniopomorskie", "km": 163}, {"slug": "torun", "name": "Toruń", "region": "kujawsko-pomorskie", "km": 184}];
export const LOC: Record<string, string> = {"Poznań": "Poznaniu", "Zielona Góra": "Zielonej Górze", "Gorzów Wielkopolski": "Gorzowie Wielkopolskim", "Leszno": "Lesznie", "Wrocław": "Wrocławiu", "Bydgoszcz": "Bydgoszczy", "Toruń": "Toruniu", "Szczecin": "Szczecinie", "Kalisz": "Kaliszu", "Konin": "Koninie", "Piła": "Pile", "Legnica": "Legnicy", "Głogów": "Głogowie", "Gniezno": "Gnieźnie", "Ostrów Wielkopolski": "Ostrowie Wielkopolskim", "Świebodzin": "Świebodzinie", "Nowy Tomyśl": "Nowym Tomyślu", "Grodzisk Wielkopolski": "Grodzisku Wielkopolskim", "Wolsztyn": "Wolsztynie", "Międzyrzecz": "Międzyrzeczu", "Szamotuły": "Szamotułach", "Śrem": "Śremie", "Kościan": "Kościanie", "Lubin": "Lubinie", "Nowa Sól": "Nowej Soli", "Żary": "Żarach", "Inowrocław": "Inowrocławiu"};
export const REGIONS = Array.from(new Set(CITIES.map((c) => c.region)));
export const SUPABASE_URL = process.env.VITE_SUPABASE_URL ?? "https://ihehncaaokbwbdqdztna.supabase.co";
export const ANON = process.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZWhuY2Fhb2tid2JkcWR6dG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwODUyMDMsImV4cCI6MjA5NzY2MTIwM30.jZCKRCmzNRymVoeSJfXuL6v3qemE8NfV5qmNvpFjqi8";
export function esc(s: unknown) { return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string)); }
export async function rpc(name: string, body: Record<string, unknown>) {
  const r = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, { method: "POST", headers: { apikey: ANON, Authorization: `Bearer ${ANON}`, "Content-Type": "application/json", "Content-Profile": "market", "Accept-Profile": "market" }, body: JSON.stringify(body) });
  return r.ok ? r.json() : [];
}
export function zl(n: number) { return new Intl.NumberFormat("pl-PL", { style: "currency", currency: "PLN", maximumFractionDigits: 2 }).format(n); }
